//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamIntJul2021.AppBase.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("XamIntJul2021.AppBase.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string PageTitleLanguage {
            get {
                return ResourceManager.GetString("PageTitleLanguage", resourceCulture);
            }
        }
        
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        public static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        public static string PageTitleTerms {
            get {
                return ResourceManager.GetString("PageTitleTerms", resourceCulture);
            }
        }
        
        public static string PageTitleMainMenu {
            get {
                return ResourceManager.GetString("PageTitleMainMenu", resourceCulture);
            }
        }
        
        public static string PageTitleNewReport {
            get {
                return ResourceManager.GetString("PageTitleNewReport", resourceCulture);
            }
        }
        
        public static string PageTitleLocations {
            get {
                return ResourceManager.GetString("PageTitleLocations", resourceCulture);
            }
        }
        
        public static string PageTitleSync {
            get {
                return ResourceManager.GetString("PageTitleSync", resourceCulture);
            }
        }
        
        public static string PageTitleAbout {
            get {
                return ResourceManager.GetString("PageTitleAbout", resourceCulture);
            }
        }
        
        public static string PageTitleReport {
            get {
                return ResourceManager.GetString("PageTitleReport", resourceCulture);
            }
        }
        
        public static string AboutDeviceName {
            get {
                return ResourceManager.GetString("AboutDeviceName", resourceCulture);
            }
        }
        
        public static string AboutDevicePlatform {
            get {
                return ResourceManager.GetString("AboutDevicePlatform", resourceCulture);
            }
        }
        
        public static string AboutDeviceSystemVersion {
            get {
                return ResourceManager.GetString("AboutDeviceSystemVersion", resourceCulture);
            }
        }
        
        public static string AboutDeviceManufacturer {
            get {
                return ResourceManager.GetString("AboutDeviceManufacturer", resourceCulture);
            }
        }
        
        public static string AboutDeviceModel {
            get {
                return ResourceManager.GetString("AboutDeviceModel", resourceCulture);
            }
        }
        
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        public static string NotConnectedError {
            get {
                return ResourceManager.GetString("NotConnectedError", resourceCulture);
            }
        }
        
        public static string UserCreatedMessage {
            get {
                return ResourceManager.GetString("UserCreatedMessage", resourceCulture);
            }
        }
        
        public static string TimeoutMessage {
            get {
                return ResourceManager.GetString("TimeoutMessage", resourceCulture);
            }
        }
        
        public static string UnauthorizedMessage {
            get {
                return ResourceManager.GetString("UnauthorizedMessage", resourceCulture);
            }
        }
        
        public static string ServerErrorMessage {
            get {
                return ResourceManager.GetString("ServerErrorMessage", resourceCulture);
            }
        }
        
        public static string UserCreatedTitle {
            get {
                return ResourceManager.GetString("UserCreatedTitle", resourceCulture);
            }
        }
        
        public static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        public static string UserCreationErrorTitle {
            get {
                return ResourceManager.GetString("UserCreationErrorTitle", resourceCulture);
            }
        }
        
        public static string SuccessLoginMessage {
            get {
                return ResourceManager.GetString("SuccessLoginMessage", resourceCulture);
            }
        }
        
        public static string ErrorLoginMessage {
            get {
                return ResourceManager.GetString("ErrorLoginMessage", resourceCulture);
            }
        }
        
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        public static string UserInfoSuccessMessage {
            get {
                return ResourceManager.GetString("UserInfoSuccessMessage", resourceCulture);
            }
        }
        
        public static string UserInfoErrorMessage {
            get {
                return ResourceManager.GetString("UserInfoErrorMessage", resourceCulture);
            }
        }
        
        public static string GetBranchesSuccessMessage {
            get {
                return ResourceManager.GetString("GetBranchesSuccessMessage", resourceCulture);
            }
        }
        
        public static string GetBranchesErrorMessage {
            get {
                return ResourceManager.GetString("GetBranchesErrorMessage", resourceCulture);
            }
        }
        
        public static string BranchDetailTitle {
            get {
                return ResourceManager.GetString("BranchDetailTitle", resourceCulture);
            }
        }
        
        public static string CurrentLocationLabel {
            get {
                return ResourceManager.GetString("CurrentLocationLabel", resourceCulture);
            }
        }
        
        public static string GetLocationErrorTitle {
            get {
                return ResourceManager.GetString("GetLocationErrorTitle", resourceCulture);
            }
        }
        
        public static string GetLocationNotSupportedError {
            get {
                return ResourceManager.GetString("GetLocationNotSupportedError", resourceCulture);
            }
        }
        
        public static string GetLocationNotEnabledError {
            get {
                return ResourceManager.GetString("GetLocationNotEnabledError", resourceCulture);
            }
        }
        
        public static string GetLocationPermissionError {
            get {
                return ResourceManager.GetString("GetLocationPermissionError", resourceCulture);
            }
        }
        
        public static string OriginPinLabel {
            get {
                return ResourceManager.GetString("OriginPinLabel", resourceCulture);
            }
        }
        
        public static string DestinationPinLabel {
            get {
                return ResourceManager.GetString("DestinationPinLabel", resourceCulture);
            }
        }
        
        public static string ProgressBarHeader {
            get {
                return ResourceManager.GetString("ProgressBarHeader", resourceCulture);
            }
        }
        
        public static string PageTitlePreviewPhoto {
            get {
                return ResourceManager.GetString("PageTitlePreviewPhoto", resourceCulture);
            }
        }
    }
}
